package de.blinkt.openvpn.activities;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.VpnService;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.util.Base64;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.StringReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import de.blinkt.openvpn.VpnProfile;
import de.blinkt.openvpn.core.ConfigParser;
import de.blinkt.openvpn.core.ConnectionStatus;
import de.blinkt.openvpn.core.ProfileManager;
import de.blinkt.openvpn.core.VPNLaunchHelper;
import de.blinkt.openvpn.core.VpnStatus;

public class NazarVPNActivity extends Activity implements VpnStatus.StateListener, VpnStatus.ByteCountListener {
    private static final int REQ_VPN=401;
    private static final String VPNGATE="https://www.vpngate.net/api/iphone/";
    private static final String SB="https://cdidgehrcnapaqdxmhok.supabase.co";
    private static final String KEY="sb_publishable_bj2ER2qqjx6bA7GA57-N3w_SNMPkooE";
    private static final int HOME=0, LOCATIONS=1, PREMIUM=2, SETTINGS=3, ADMIN=4;
    private static final long CACHE_MS=5*60*1000L;

    private static final Country[] ALL={
      new Country("SG","Singapore","🇸🇬","guest"),new Country("DE","Germany","🇩🇪","guest"),new Country("NL","Netherlands","🇳🇱","guest"),
      new Country("JP","Japan","🇯🇵","account"),new Country("US","United States","🇺🇸","paid"),new Country("GB","United Kingdom","🇬🇧","paid"),
      new Country("AE","United Arab Emirates","🇦🇪","paid"),new Country("TR","Turkey","🇹🇷","paid"),new Country("CA","Canada","🇨🇦","paid"),
      new Country("AU","Australia","🇦🇺","premium"),new Country("CH","Switzerland","🇨🇭","premium"),new Country("FR","France","🇫🇷","premium"),
      new Country("SE","Sweden","🇸🇪","premium"),new Country("KR","South Korea","🇰🇷","premium")
    };

    private FrameLayout content; private LinearLayout nav;
    private TextView statusText,timerText,trafficText,powerIcon,locationText,qualityText;
    private Button powerButton;
    private final ExecutorService worker=Executors.newFixedThreadPool(3); private final Handler main=new Handler(Looper.getMainLooper());
    private SharedPreferences prefs;
    private String selectedCode="AUTO",activeCountry="",activeCode="",activeQuality="";
    private boolean connected=false,connecting=false,userDisconnect=false,smartSwitch=true,signupEnabled=true;
    private long connectedAt=0,bytesIn=0,bytesOut=0,lastRelayFetch=0;
    private String accessToken="",refreshToken="",email="",role="guest",plan="free";
    private List<Relay> relayCache=new ArrayList<>(); private final Map<String,Boolean> remoteEnabled=new HashMap<>();
    private final Map<String,Relay> bestByCountry=new HashMap<>();
    private final List<Candidate> candidates=new ArrayList<>(); private int candidateIndex=-1;
    private VpnProfile pendingProfile;

    private final Runnable clock=new Runnable(){@Override public void run(){if(!connected)return;long s=Math.max(0,(System.currentTimeMillis()-connectedAt)/1000);if(timerText!=null)timerText.setText(String.format(Locale.US,"%02d:%02d:%02d",s/3600,(s%3600)/60,s%60));if(trafficText!=null)trafficText.setText(human(bytesIn)+" ↓   "+human(bytesOut)+" ↑");main.postDelayed(this,1000);}};
    private final Runnable smartMonitor=new Runnable(){@Override public void run(){if(connected&&smartSwitch&&"AUTO".equals(selectedCode))worker.execute(()->{try{List<Relay> r=fetchRelays(false);Relay best=bestAllowed(r);Relay cur=findBest(r,activeCode);if(best!=null&&cur!=null&&!best.countryShort.equals(activeCode)&&best.ping>0&&cur.ping>0&&best.ping+80<cur.ping){main.post(()->smartReconnect(best.countryShort));}}catch(Exception ignored){}});main.postDelayed(this,120000);}};

    @Override protected void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("nazarvpn4",MODE_PRIVATE);selectedCode=prefs.getString("selected","AUTO");smartSwitch=prefs.getBoolean("smart",true);accessToken=prefs.getString("token","");refreshToken=prefs.getString("refresh","");email=prefs.getString("email","");role=prefs.getString("role",accessToken.isEmpty()?"guest":"customer");plan=prefs.getString("plan","free");setContentView(buildShell());showScreen(HOME);worker.execute(()->{try{fetchRemoteConfig();fetchRemoteCountries();fetchRelays(true);}catch(Exception ignored){}main.post(()->{if(content!=null)showScreen(HOME);});});}
    @Override protected void onResume(){super.onResume();VpnStatus.addStateListener(this);VpnStatus.addByteCountListener(this);}
    @Override protected void onPause(){VpnStatus.removeStateListener(this);VpnStatus.removeByteCountListener(this);super.onPause();}

    private View buildShell(){LinearLayout shell=column();shell.setBackgroundColor(Color.rgb(246,248,252));content=new FrameLayout(this);shell.addView(content,new LinearLayout.LayoutParams(-1,0,1f));nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setPadding(dp(8),dp(6),dp(8),dp(6));nav.setBackgroundColor(Color.WHITE);addNav("⌂","Home",HOME);addNav("◎","Locations",LOCATIONS);addNav("♛","Premium",PREMIUM);addNav("⚙","Settings",SETTINGS);shell.addView(nav,new LinearLayout.LayoutParams(-1,dp(72)));return shell;}
    private void addNav(String icon,String label,int id){LinearLayout b=column();b.setGravity(Gravity.CENTER);TextView i=text(icon,22,Color.rgb(50,65,85),true);i.setGravity(Gravity.CENTER);TextView l=text(label,11,Color.rgb(50,65,85),false);l.setGravity(Gravity.CENTER);b.addView(i,new LinearLayout.LayoutParams(-1,dp(30)));b.addView(l,new LinearLayout.LayoutParams(-1,dp(22)));b.setOnClickListener(v->showScreen(id));nav.addView(b,new LinearLayout.LayoutParams(0,-1,1));}
    private void showScreen(int id){content.removeAllViews();if(id==HOME)content.addView(buildHome());else if(id==LOCATIONS)content.addView(buildLocations());else if(id==PREMIUM)content.addView(buildPremium());else if(id==ADMIN)content.addView(buildAdmin());else content.addView(buildSettings());}

    private View buildHome(){ScrollView s=new ScrollView(this);LinearLayout r=column();r.setPadding(dp(20),dp(18),dp(20),dp(28));s.addView(r);
      LinearLayout brandRow=new LinearLayout(this);brandRow.setGravity(Gravity.CENTER_VERTICAL);brandRow.addView(text("NazarVPN",28,Color.rgb(15,40,72),true),new LinearLayout.LayoutParams(0,dp(46),1));brandRow.addView(pill(isAdmin()?"ADMIN":(loggedIn()?plan.toUpperCase(Locale.US):"GUEST")),new LinearLayout.LayoutParams(dp(78),dp(34)));r.addView(brandRow,match());
      LinearLayout accountRow=new LinearLayout(this);accountRow.setGravity(Gravity.CENTER_VERTICAL);Button account=button(loggedIn()?shortEmail():"Sign in / Sign up");account.setOnClickListener(v->{if(loggedIn())showAccountDialog();else showAuthChoice();});accountRow.addView(account,new LinearLayout.LayoutParams(0,dp(46),1));Button settings=button("⚙ Settings");settings.setOnClickListener(v->showScreen(SETTINGS));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(118),dp(46));sp.setMargins(dp(8),0,0,0);accountRow.addView(settings,sp);r.addView(accountRow,margin(0,4,0,14));
      TextView tag=text("Fast auto-selection • Live relay quality • Optional account",13,Color.rgb(103,115,132),false);tag.setPadding(0,0,0,dp(14));r.addView(tag,match());
      LinearLayout loc=card();loc.addView(text("CURRENT LOCATION",11,Color.rgb(119,130,145),true),match());String locLabel="AUTO".equals(selectedCode)?"⚡  Auto — Best available":flagFor(selectedCode)+"  "+nameFor(selectedCode);locationText=text(locLabel,19,Color.rgb(24,36,52),true);loc.addView(locationText,match());qualityText=text(selectedQuality(),13,Color.rgb(44,130,86),true);qualityText.setPadding(0,dp(5),0,0);loc.addView(qualityText,match());TextView ch=text("Change ›",14,Color.rgb(42,110,205),true);ch.setGravity(Gravity.RIGHT);ch.setOnClickListener(v->showScreen(LOCATIONS));loc.addView(ch,match());r.addView(loc,margin(0,0,0,18));
      LinearLayout hero=card();hero.setGravity(Gravity.CENTER_HORIZONTAL);hero.setPadding(dp(20),dp(23),dp(20),dp(23));String st=connected?"Protected":connecting?"Finding fastest server…":"Not connected";statusText=text(st,17,connected?Color.rgb(20,145,86):Color.rgb(112,124,140),true);statusText.setGravity(Gravity.CENTER);hero.addView(statusText,match());powerIcon=text(connected?"✓":"⏻",56,Color.WHITE,true);powerIcon.setGravity(Gravity.CENTER);powerIcon.setBackground(circle(connected?Color.rgb(24,171,101):Color.rgb(48,111,218)));powerIcon.setOnClickListener(v->toggle());LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(dp(126),dp(126));pp.setMargins(0,dp(18),0,dp(16));hero.addView(powerIcon,pp);powerButton=button(connected?"Disconnect":connecting?"Connecting…":"Quick Connect");primary(powerButton);powerButton.setEnabled(!connecting);powerButton.setOnClickListener(v->toggle());hero.addView(powerButton,new LinearLayout.LayoutParams(-1,dp(52)));timerText=text(connected?elapsed():"00:00:00",18,Color.rgb(35,47,62),true);timerText.setGravity(Gravity.CENTER);timerText.setPadding(0,dp(16),0,dp(4));hero.addView(timerText,match());trafficText=text(human(bytesIn)+" ↓   "+human(bytesOut)+" ↑",13,Color.rgb(115,126,142),false);trafficText.setGravity(Gravity.CENTER);hero.addView(trafficText,match());if(connected){TextView q=text(activeCountry+"   "+activeQuality,13,Color.rgb(25,128,82),true);q.setGravity(Gravity.CENTER);q.setPadding(0,dp(8),0,0);hero.addView(q,match());}r.addView(hero,margin(0,0,0,16));
      LinearLayout note=card();note.addView(text(loggedIn()?"Account benefit active":"Create an account — optional",16,Color.rgb(27,37,53),true),match());note.addView(text(loggedIn()?"Japan is unlocked for signed-in free customers. Admin accounts can access all enabled locations.":"VPN works as Guest. Sign up only if you want the extra Japan location and account features.",13,Color.rgb(102,112,128),false),margin(0,6,0,0));r.addView(note,match());if(connected){main.removeCallbacks(clock);main.post(clock);main.removeCallbacks(smartMonitor);main.postDelayed(smartMonitor,120000);}return s;}

    private View buildLocations(){ScrollView s=new ScrollView(this);LinearLayout r=column();r.setPadding(dp(20),dp(20),dp(20),dp(28));s.addView(r);r.addView(text("Locations",28,Color.rgb(20,35,55),true),match());r.addView(text("Signal bars are based on live relay latency/speed, not your phone's cellular bars.",13,Color.rgb(105,118,134),false),margin(0,4,0,14));r.addView(locationRow("⚡","Auto — Best available","Fastest allowed relay","AUTO",false),margin(0,4,0,7));for(Country c:ALL){boolean locked=!allowed(c);String planLabel=c.level.equals("guest")?"Free":c.level.equals("account")?"Account bonus":capitalize(c.level);r.addView(locationRow(c.flag,c.name,planLabel,c.code,locked),margin(0,4,0,7));}return s;}
    private View locationRow(String flag,String name,String sub,String code,boolean locked){LinearLayout row=card();row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),dp(9),dp(14),dp(9));row.addView(text(flag,27,Color.BLACK,false),new LinearLayout.LayoutParams(dp(50),dp(58)));LinearLayout mid=column();mid.addView(text(name,15,Color.rgb(30,42,59),true),match());mid.addView(text(sub+"  •  "+qualityFor(code),12,Color.rgb(95,108,124),false),match());row.addView(mid,new LinearLayout.LayoutParams(0,dp(58),1));TextView end=text(locked?"🔒":code.equals(selectedCode)?"✓":"›",18,locked?Color.GRAY:Color.rgb(36,111,210),true);end.setGravity(Gravity.CENTER);row.addView(end,new LinearLayout.LayoutParams(dp(42),dp(58)));row.setOnClickListener(v->{if(locked){if("account".equals(levelFor(code))&&!loggedIn())showAuthChoice();else showScreen(PREMIUM);}else{selectedCode=code;prefs.edit().putString("selected",code).apply();showScreen(HOME);}});return row;}

    private View buildSettings(){ScrollView s=new ScrollView(this);LinearLayout r=column();r.setPadding(dp(20),dp(20),dp(20),dp(28));s.addView(r);r.addView(text("Settings",28,Color.rgb(20,35,55),true),match());r.addView(text("Connection and account controls",13,Color.rgb(108,119,134),false),margin(0,4,0,14));View a=setting("👤",loggedIn()?"Account":"Sign in / Sign up",loggedIn()?email:"Optional — Guest mode remains available",loggedIn()?"›":"JOIN");a.setOnClickListener(v->{if(loggedIn())showAccountDialog();else showAuthChoice();});r.addView(a,margin(0,5,0,5));View auto=setting("⚡","Auto location","Choose the best available allowed country","AUTO");auto.setOnClickListener(v->{selectedCode="AUTO";prefs.edit().putString("selected","AUTO").apply();Toast.makeText(this,"Auto location enabled",Toast.LENGTH_SHORT).show();showScreen(HOME);});r.addView(auto,margin(0,5,0,5));View smart=setting("⇄","Smart Switch","Switch on future checks when another relay is much better",smartSwitch?"ON":"OFF");smart.setOnClickListener(v->{smartSwitch=!smartSwitch;prefs.edit().putBoolean("smart",smartSwitch).apply();showScreen(SETTINGS);});r.addView(smart,margin(0,5,0,5));r.addView(setting("🛡","VPN engine","Embedded OpenVPN / Android VpnService","LIVE"),margin(0,5,0,5));if(isAdmin()){View ad=setting("⚙","Admin Panel","Signup, countries and connection controls","OPEN");ad.setOnClickListener(v->showScreen(ADMIN));r.addView(ad,margin(0,5,0,5));}r.addView(setting("?","Support","EasyPaisa 03434710858","›"),margin(0,5,0,5));return s;}

    private View buildAdmin(){ScrollView s=new ScrollView(this);LinearLayout r=column();r.setPadding(dp(20),dp(20),dp(20),dp(28));s.addView(r);r.addView(text("Admin Panel",28,Color.rgb(20,35,55),true),match());if(!isAdmin()){r.addView(text("Admin access required.",15,Color.RED,true),margin(0,16,0,0));return s;}r.addView(text("Your admin account can use every location regardless of customer plan.",13,Color.rgb(105,118,134),false),margin(0,4,0,14));Button signup=button("Customer signup: "+(signupEnabled?"ON":"OFF"));primary(signup);signup.setOnClickListener(v->adminPatchConfig("signup_enabled",!signupEnabled));r.addView(signup,new LinearLayout.LayoutParams(-1,dp(50)));r.addView(section("COUNTRY AVAILABILITY"),margin(0,16,0,4));for(Country c:ALL){boolean en=countryEnabled(c.code);LinearLayout row=card();row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(text(c.flag+"  "+c.name,14,Color.rgb(34,46,62),true),new LinearLayout.LayoutParams(0,dp(46),1));Button b=button(en?"Enabled":"Disabled");b.setOnClickListener(v->adminCountry(c.code,!en));row.addView(b,new LinearLayout.LayoutParams(dp(110),dp(44)));r.addView(row,margin(0,4,0,4));}return s;}

    private View buildPremium(){ScrollView s=new ScrollView(this);LinearLayout r=column();r.setPadding(dp(20),dp(20),dp(20),dp(28));s.addView(r);r.addView(text("NazarVPN Premium",28,Color.rgb(20,35,55),true),match());r.addView(planCard("PAID","Rs 1,000","More countries\nPriority options"),margin(0,14,0,8));r.addView(planCard("PREMIUM","Rs 5,000","All customer locations\nAdvanced options"),margin(0,4,0,12));LinearLayout p=card();p.addView(text("EasyPaisa",16,Color.rgb(30,42,57),true),match());p.addView(text("03434710858",24,Color.rgb(20,130,80),true),margin(0,6,0,4));p.addView(text("Send payment and contact support for activation.",13,Color.rgb(103,114,129),false),match());r.addView(p,match());return s;}
    private View planCard(String n,String price,String features){LinearLayout c=card();c.addView(text(n,13,Color.rgb(42,109,201),true),match());c.addView(text(price,28,Color.rgb(25,36,52),true),margin(0,5,0,10));c.addView(text(features,14,Color.rgb(100,111,126),false),margin(0,0,0,12));Button b=button("Get "+n);dark(b);b.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(n+" activation").setMessage("Send "+price+" to EasyPaisa 03434710858 and contact NazarVPN support.").setPositiveButton("OK",null).show());c.addView(b,new LinearLayout.LayoutParams(-1,dp(48)));return c;}

    private void showAuthChoice(){if(!signupEnabled){showLoginDialog(false);return;}new AlertDialog.Builder(this).setTitle("NazarVPN account").setMessage("Account is optional. You can keep using Guest mode, or sign in/sign up to unlock Japan.").setPositiveButton("Sign up",(d,w)->showLoginDialog(true)).setNegativeButton("Sign in",(d,w)->showLoginDialog(false)).setNeutralButton("Continue as Guest",null).show();}
    private void showLoginDialog(boolean signup){LinearLayout box=column();box.setPadding(dp(18),dp(4),dp(18),0);EditText em=new EditText(this);em.setHint("Email");em.setSingleLine(true);EditText pw=new EditText(this);pw.setHint("Password (6+ characters)");pw.setSingleLine(true);pw.setInputType(0x81);box.addView(em,match());box.addView(pw,match());new AlertDialog.Builder(this).setTitle(signup?"Create account":"Sign in").setView(box).setPositiveButton(signup?"Sign up":"Sign in",(d,w)->{String e=em.getText().toString().trim();String p=pw.getText().toString();if(e.isEmpty()||p.length()<6){Toast.makeText(this,"Enter a valid email and password",Toast.LENGTH_LONG).show();return;}worker.execute(()->auth(e,p,signup));}).setNegativeButton("Cancel",null).show();}
    private void auth(String em,String pw,boolean signup){try{JSONObject body=new JSONObject();body.put("email",em);body.put("password",pw);String path=signup?"/auth/v1/signup":"/auth/v1/token?grant_type=password";String out=request("POST",SB+path,body.toString(),null);JSONObject j=new JSONObject(out);String tok=j.optString("access_token","");if(tok.isEmpty()){main.post(()->new AlertDialog.Builder(this).setTitle("Check your email").setMessage("Account created. Confirm your email, then return to NazarVPN and sign in to unlock Japan.").setPositiveButton("OK",null).show());return;}accessToken=tok;refreshToken=j.optString("refresh_token","");email=em;loadProfile();saveSession();main.post(()->{Toast.makeText(this,signup?"Account ready — Japan unlocked":"Signed in",Toast.LENGTH_LONG).show();showScreen(HOME);});}catch(Exception e){main.post(()->new AlertDialog.Builder(this).setTitle(signup?"Sign up failed":"Sign in failed").setMessage(safe(e)).setPositiveButton("OK",null).show());}}
    private void loadProfile() throws Exception{String out=request("GET",SB+"/rest/v1/nazarvpn_profiles?select=role,plan,bonus_country,is_active&limit=1",null,accessToken);JSONArray a=new JSONArray(out);if(a.length()>0){JSONObject p=a.getJSONObject(0);role=p.optString("role","customer");plan=p.optString("plan","free");}else{role="customer";plan="free";}}
    private void saveSession(){prefs.edit().putString("token",accessToken).putString("refresh",refreshToken).putString("email",email).putString("role",role).putString("plan",plan).apply();}
    private void showAccountDialog(){new AlertDialog.Builder(this).setTitle(isAdmin()?"Admin account":"NazarVPN account").setMessage(email+"\nPlan: "+plan+"\nRole: "+role+(isAdmin()?"\nAll locations are available to this admin account.":"\nJapan bonus location is unlocked.")).setPositiveButton(isAdmin()?"Admin Panel":"OK",(d,w)->{if(isAdmin())showScreen(ADMIN);}).setNegativeButton("Sign out",(d,w)->signOut()).show();}
    private void signOut(){accessToken=refreshToken=email="";role="guest";plan="free";prefs.edit().remove("token").remove("refresh").remove("email").remove("role").remove("plan").apply();if(!allowedCode(selectedCode))selectedCode="AUTO";showScreen(HOME);}

    private void toggle(){if(connected){disconnectInternal(true);return;}if(connecting)return;userDisconnect=false;connecting=true;showScreen(HOME);worker.execute(this::prepareCandidates);}
    private void prepareCandidates(){try{List<Relay> relays=fetchRelays(false);List<Relay> filtered=new ArrayList<>();for(Relay x:relays)if(allowedCode(x.countryShort)&&countryEnabled(x.countryShort)&&("AUTO".equals(selectedCode)||selectedCode.equalsIgnoreCase(x.countryShort)))filtered.add(x);if(filtered.isEmpty()&&!"AUTO".equals(selectedCode)){for(Relay x:relays)if(allowedCode(x.countryShort)&&countryEnabled(x.countryShort))filtered.add(x);}String last=prefs.getString("last_good_ip","");Collections.sort(filtered,(a,b)->Long.compare(rank(b)+(b.ip.equals(last)?100000000000L:0),rank(a)+(a.ip.equals(last)?100000000000L:0)));candidates.clear();for(Relay relay:filtered){if(candidates.size()>=6)break;try{String ovpn=new String(Base64.decode(relay.config,Base64.DEFAULT),StandardCharsets.UTF_8);ConfigParser cp=new ConfigParser();cp.parseConfig(new StringReader(ovpn));VpnProfile vp=cp.convertProfile();vp.mName="NazarVPN - "+relay.countryLong+" "+bars(relay.ping);ProfileManager.setTemporaryProfile(this,vp);Candidate c=new Candidate();c.profile=vp;c.relay=relay;candidates.add(c);}catch(Exception ignored){}}if(candidates.isEmpty())throw new Exception("No compatible live relay found");candidateIndex=-1;main.post(this::startNextCandidate);}catch(Exception e){main.post(()->failConnect("Could not find a live VPN relay.\n\n"+safe(e)));}}
    private void startNextCandidate(){candidateIndex++;if(candidateIndex>=candidates.size()){failConnect("All available relays were busy. Please try again.");return;}Candidate c=candidates.get(candidateIndex);pendingProfile=c.profile;activeCountry=c.relay.countryLong;activeCode=c.relay.countryShort;activeQuality=quality(c.relay);requestVpnPermission();}
    private void requestVpnPermission(){Intent i=VpnService.prepare(this);if(i!=null)startActivityForResult(i,REQ_VPN);else startPending();}
    private void startPending(){try{VPNLaunchHelper.startOpenVpn(pendingProfile,getApplicationContext(),"NazarVPN Smart Connect",true);statusIf("Connecting to "+activeCountry+"…");}catch(Exception e){main.postDelayed(this::startNextCandidate,300);}}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==REQ_VPN){if(result==RESULT_OK)startPending();else failConnect("VPN permission is required.");}}
    private void failConnect(String m){connecting=false;connected=false;showScreen(HOME);new AlertDialog.Builder(this).setTitle("Could not connect").setMessage(m).setPositiveButton("OK",null).show();}
    private void disconnectInternal(boolean user){userDisconnect=user;try{startActivity(new Intent(this,de.blinkt.openvpn.activities.DisconnectVPN.class));}catch(Exception e){Toast.makeText(this,"Could not disconnect",Toast.LENGTH_SHORT).show();}}
    private void smartReconnect(String code){if(!connected)return;Toast.makeText(this,"A faster relay is available — switching…",Toast.LENGTH_SHORT).show();disconnectInternal(false);main.postDelayed(()->{selectedCode="AUTO";connected=false;connecting=false;toggle();},1800);}

    @Override public void updateState(String state,String log,int resid,ConnectionStatus level,Intent intent){runOnUiThread(()->{if(level==ConnectionStatus.LEVEL_CONNECTED){connected=true;connecting=false;connectedAt=System.currentTimeMillis();if(candidateIndex>=0&&candidateIndex<candidates.size()){Relay r=candidates.get(candidateIndex).relay;activeCountry=r.countryLong;activeCode=r.countryShort;activeQuality=quality(r);prefs.edit().putString("last_good_ip",r.ip).putString("last_good_country",r.countryShort).apply();}showScreen(HOME);}else if(level==ConnectionStatus.LEVEL_NOTCONNECTED||level==ConnectionStatus.LEVEL_AUTH_FAILED){connected=false;connectedAt=0;main.removeCallbacks(clock);if(connecting&&!userDisconnect&&candidateIndex+1<candidates.size())main.postDelayed(this::startNextCandidate,350);else{connecting=false;if(!userDisconnect&&candidateIndex>=0)Toast.makeText(this,"Relay unavailable — choose Auto and retry",Toast.LENGTH_SHORT).show();showScreen(HOME);}}else if(level==ConnectionStatus.LEVEL_CONNECTING_NO_SERVER_REPLY_YET||level==ConnectionStatus.LEVEL_CONNECTING_SERVER_REPLIED){connecting=true;statusIf("Connecting to "+activeCountry+"…");}});}
    @Override public void setConnectedVPN(String uuid){}
    @Override public void updateByteCount(long in,long out,long di,long dout){bytesIn=in;bytesOut=out;runOnUiThread(()->{if(trafficText!=null)trafficText.setText(human(in)+" ↓   "+human(out)+" ↑");});}

    private List<Relay> fetchRelays(boolean warm) throws Exception{if(!relayCache.isEmpty()&&System.currentTimeMillis()-lastRelayFetch<CACHE_MS)return new ArrayList<>(relayCache);HttpURLConnection c=(HttpURLConnection)new URL(VPNGATE).openConnection();c.setConnectTimeout(6000);c.setReadTimeout(9000);c.setRequestProperty("User-Agent","NazarVPN/4.0 Android");if(c.getResponseCode()!=200)throw new Exception("VPN directory unavailable");List<Relay> out=new ArrayList<>();try(BufferedReader br=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8))){String line;while((line=br.readLine())!=null){if(line.startsWith("*")||line.startsWith("#")||line.trim().isEmpty())continue;String[] p=line.split(",",15);if(p.length<15)continue;try{Relay r=new Relay();r.host=p[0];r.ip=p[1];r.score=parseLong(p[2]);r.ping=(int)parseLong(p[3]);r.speed=parseLong(p[4]);r.countryLong=p[5];r.countryShort=p[6];r.config=p[14];if(!r.config.isEmpty())out.add(r);}catch(Exception ignored){}}}finally{c.disconnect();}relayCache=out;lastRelayFetch=System.currentTimeMillis();bestByCountry.clear();for(Relay r:out){Relay old=bestByCountry.get(r.countryShort);if(old==null||rank(r)>rank(old))bestByCountry.put(r.countryShort,r);}return new ArrayList<>(out);}
    private Relay bestAllowed(List<Relay> rs){Relay best=null;for(Relay r:rs)if(allowedCode(r.countryShort)&&countryEnabled(r.countryShort)&&(best==null||rank(r)>rank(best)))best=r;return best;}
    private Relay findBest(List<Relay> rs,String code){Relay b=null;for(Relay r:rs)if(code.equals(r.countryShort)&&(b==null||rank(r)>rank(b)))b=r;return b;}
    private long rank(Relay r){long pingPenalty=r.ping>0?r.ping*300000L:50000000L;return r.speed+r.score*20-pingPenalty;}

    private void fetchRemoteConfig(){try{String o=request("GET",SB+"/rest/v1/nazarvpn_app_config?select=signup_enabled&limit=1",null,null);JSONArray a=new JSONArray(o);if(a.length()>0)signupEnabled=a.getJSONObject(0).optBoolean("signup_enabled",true);}catch(Exception ignored){}}
    private void fetchRemoteCountries(){try{String o=request("GET",SB+"/rest/v1/nazarvpn_countries?select=code,enabled",null,null);JSONArray a=new JSONArray(o);for(int i=0;i<a.length();i++){JSONObject j=a.getJSONObject(i);remoteEnabled.put(j.optString("code"),j.optBoolean("enabled",true));}}catch(Exception ignored){}}
    private void adminPatchConfig(String key,boolean value){if(!isAdmin())return;worker.execute(()->{try{JSONObject b=new JSONObject();b.put(key,value);request("PATCH",SB+"/rest/v1/nazarvpn_app_config?id=eq.1",b.toString(),accessToken);signupEnabled=value;main.post(()->{Toast.makeText(this,"Admin setting updated",Toast.LENGTH_SHORT).show();showScreen(ADMIN);});}catch(Exception e){main.post(()->Toast.makeText(this,safe(e),Toast.LENGTH_LONG).show());}});}
    private void adminCountry(String code,boolean enabled){if(!isAdmin())return;worker.execute(()->{try{JSONObject b=new JSONObject();b.put("enabled",enabled);request("PATCH",SB+"/rest/v1/nazarvpn_countries?code=eq."+code,b.toString(),accessToken);remoteEnabled.put(code,enabled);main.post(()->showScreen(ADMIN));}catch(Exception e){main.post(()->Toast.makeText(this,safe(e),Toast.LENGTH_LONG).show());}});}
    private String request(String method,String url,String body,String token) throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod(method);c.setConnectTimeout(8000);c.setReadTimeout(10000);c.setRequestProperty("apikey",KEY);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Accept","application/json");if(token!=null&&!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if("PATCH".equals(method))c.setRequestProperty("Prefer","return=representation");if(body!=null){c.setDoOutput(true);try(OutputStream os=c.getOutputStream()){os.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();StringBuilder sb=new StringBuilder();if(in!=null)try(BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String l;while((l=br.readLine())!=null)sb.append(l);}c.disconnect();if(code<200||code>=300){String msg=sb.toString();try{JSONObject j=new JSONObject(msg);msg=j.optString("msg",j.optString("message",j.optString("error_description",msg)));}catch(Exception ignored){}throw new Exception(msg.isEmpty()?"HTTP "+code:msg);}return sb.toString();}

    private boolean loggedIn(){return !accessToken.isEmpty();}private boolean isAdmin(){return "admin".equalsIgnoreCase(role);}private boolean allowed(Country c){if(isAdmin())return true;if("guest".equals(c.level))return countryEnabled(c.code);if("account".equals(c.level))return loggedIn()&&countryEnabled(c.code);if("paid".equals(c.level))return loggedIn()&&("paid".equals(plan)||"premium".equals(plan))&&countryEnabled(c.code);return loggedIn()&&"premium".equals(plan)&&countryEnabled(c.code);}private boolean allowedCode(String code){if("AUTO".equals(code))return true;for(Country c:ALL)if(c.code.equals(code))return allowed(c);return false;}private boolean countryEnabled(String code){if(isAdmin())return true;Boolean b=remoteEnabled.get(code);return b==null||b;}private String levelFor(String code){for(Country c:ALL)if(c.code.equals(code))return c.level;return"guest";}
    private String selectedQuality(){if("AUTO".equals(selectedCode)){Relay b=bestAllowed(relayCache);return b==null?"Live quality will appear automatically":"Best now: "+b.countryLong+"  "+quality(b);}Relay r=bestByCountry.get(selectedCode);return r==null?"Checking live signal…":quality(r);}private String qualityFor(String code){if("AUTO".equals(code)){Relay b=bestAllowed(relayCache);return b==null?"checking":quality(b);}Relay r=bestByCountry.get(code);return r==null?"checking":quality(r);}private String quality(Relay r){return bars(r.ping)+(r.ping>0?"  "+r.ping+" ms":"")+(r.speed>0?"  "+speed(r.speed):"");}private String bars(int ping){if(ping<=0)return"▂▄";if(ping<70)return"▂▄▆█";if(ping<130)return"▂▄▆";if(ping<220)return"▂▄";return"▂";}private String speed(long bps){double m=bps/1000000d;return String.format(Locale.US,"%.1f Mbps",m);}private static long parseLong(String s){try{return Long.parseLong(s.trim());}catch(Exception e){return 0;}}
    private String nameFor(String code){for(Country c:ALL)if(c.code.equals(code))return c.name;return code;}private String flagFor(String code){for(Country c:ALL)if(c.code.equals(code))return c.flag;return"🌐";}private String shortEmail(){if(email.length()<22)return email;return email.substring(0,19)+"…";}private String capitalize(String s){return s.substring(0,1).toUpperCase(Locale.US)+s.substring(1);}private void statusIf(String s){if(statusText!=null)statusText.setText(s);if(powerButton!=null)powerButton.setText(s);}private String elapsed(){if(connectedAt==0)return"00:00:00";long s=(System.currentTimeMillis()-connectedAt)/1000;return String.format(Locale.US,"%02d:%02d:%02d",s/3600,(s%3600)/60,s%60);}private String human(long b){if(b<1024)return b+" B";double k=b/1024d;if(k<1024)return String.format(Locale.US,"%.1f KB",k);double m=k/1024d;if(m<1024)return String.format(Locale.US,"%.1f MB",m);return String.format(Locale.US,"%.2f GB",m/1024d);}private String safe(Exception e){String m=e.getMessage();return m==null||m.trim().isEmpty()?e.getClass().getSimpleName():m;}
    private TextView text(String v,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(sp);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private TextView pill(String v){TextView t=text(v,10,Color.rgb(25,100,180),true);t.setGravity(Gravity.CENTER);t.setBackground(round(Color.rgb(232,244,255),18));return t;}private TextView section(String v){TextView t=text(v,11,Color.rgb(115,126,140),true);t.setPadding(dp(4),dp(4),0,dp(6));return t;}private Button button(String v){Button b=new Button(this);b.setText(v);b.setAllCaps(false);b.setTextSize(13);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return b;}private void primary(Button b){b.setTextColor(Color.WHITE);b.setBackground(round(Color.rgb(48,111,218),16));}private void dark(Button b){b.setTextColor(Color.WHITE);b.setBackground(round(Color.rgb(26,39,60),16));}private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private LinearLayout card(){LinearLayout l=column();l.setPadding(dp(17),dp(15),dp(17),dp(15));l.setBackground(round(Color.WHITE,22));l.setElevation(dp(2));return l;}private View setting(String icon,String title,String desc,String end){LinearLayout row=card();row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),dp(9),dp(14),dp(9));row.addView(text(icon,21,Color.rgb(45,91,155),false),new LinearLayout.LayoutParams(dp(44),dp(54)));row.addView(text(title+"\n"+desc,14,Color.rgb(35,46,61),true),new LinearLayout.LayoutParams(0,dp(54),1));TextView e=text(end,11,Color.rgb(83,96,114),true);e.setGravity(Gravity.CENTER);row.addView(e,new LinearLayout.LayoutParams(dp(62),dp(54)));return row;}private GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}private GradientDrawable circle(int color){GradientDrawable g=new GradientDrawable();g.setShape(GradientDrawable.OVAL);g.setColor(color);return g;}private LinearLayout.LayoutParams match(){return new LinearLayout.LayoutParams(-1,-2);}private LinearLayout.LayoutParams margin(int l,int t,int r,int b){LinearLayout.LayoutParams p=match();p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    @Override protected void onDestroy(){main.removeCallbacks(clock);main.removeCallbacks(smartMonitor);worker.shutdownNow();super.onDestroy();}
    private static class Country{String code,name,flag,level;Country(String c,String n,String f,String l){code=c;name=n;flag=f;level=l;}}
    private static class Relay{String host,ip,countryLong,countryShort,config;long score,speed;int ping;}
    private static class Candidate{VpnProfile profile;Relay relay;}
}
